name: japhy_todo_app
description: A Flutter To-Do app called Japhy.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  table_calendar: ^3.0.9
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  flutter_local_notifications: ^18.0.1
  intl: ^0.18.1
  timezone: ^0.10.1
  uuid: ^4.3.1

flutter_local_notifications:
  default_os_configs:
    linux:
      default_package: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
