name: japhy_todo_app
description: A Flutter To-Do app called Japhy.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  provider: ^6.0.5

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.1.0

  # Utilities
  image_picker: ^1.0.7
  uuid: ^4.3.1
  intl: ^0.20.2
  timezone: ^0.10.1
  google_sign_in: ^6.2.1

  # Notifications
  flutter_local_notifications: ^19.3.0

  # ✅ Google sign-in styled buttons
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
