// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAf1ny-pdfYvFDUABadMDVbxQavYbP0W0',
    appId: '1:300397427222:web:95fb491dee00bdb2e61337',
    messagingSenderId: '300397427222',
    projectId: 'japhy-b63de',
    authDomain: 'japhy-b63de.firebaseapp.com',
    storageBucket: 'japhy-b63de.firebasestorage.app',
    measurementId: 'G-PH2243FTQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyv9aYpTz6PjqwO4TsgidifWA1R1PdKEY',
    appId: '1:300397427222:android:4d9a7723387c28c5e61337',
    messagingSenderId: '300397427222',
    projectId: 'japhy-b63de',
    storageBucket: 'japhy-b63de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD63Yl2yY3_6MxqFC3AbCiYvBu2qRnGiOU',
    appId: '1:300397427222:ios:83645e8ff1ec33c7e61337',
    messagingSenderId: '300397427222',
    projectId: 'japhy-b63de',
    storageBucket: 'japhy-b63de.firebasestorage.app',
    iosBundleId: 'com.example.japhy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD63Yl2yY3_6MxqFC3AbCiYvBu2qRnGiOU',
    appId: '1:300397427222:ios:83645e8ff1ec33c7e61337',
    messagingSenderId: '300397427222',
    projectId: 'japhy-b63de',
    storageBucket: 'japhy-b63de.firebasestorage.app',
    iosBundleId: 'com.example.japhy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAf1ny-pdfYvFDUABadMDVbxQavYbP0W0',
    appId: '1:300397427222:web:084771320805828ae61337',
    messagingSenderId: '300397427222',
    projectId: 'japhy-b63de',
    authDomain: 'japhy-b63de.firebaseapp.com',
    storageBucket: 'japhy-b63de.firebasestorage.app',
    measurementId: 'G-N8HDDE1P1F',
  );
}
